// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import { Roboto_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// const robotoMono = Roboto_Mono({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-roboto-mono",
// });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
        <Toaster
          richColors
          position="bottom-left"
          duration={2500}
          toastOptions={{ style: { padding: "15px", fontSize: "1.25rem" } }}
        />
      </body>
    </html>
  );
}
